apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.component_id }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.component_id }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ${{ values.component_id }}
    spec:
      containers:
        - name: ${{ values.component_id }}
          image: docker.com:8083/punasusi/${{ values.component_id }}:0.0.0
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512M
            requests:
              cpu: 200m
              memory: 256M
      imagePullSecrets:
        - name: regcred
